###
GET http://localhost:3000/building
###
GET http://localhost:3000/building/17fc9a7e-80b5-4027-a5b5-8552f340fc15
###
POST http://localhost:3000/building
Content-Type: application/json

{
  "name": "New Building",
  "description": "Description of New Building",
  "numberFloor": 7,
  "imageCover": "newbuilding.jpg",
  "areaId": "123"
}
###
PUT http://localhost:3000/building/17fc9a7e-80b5-4027-a5b5-8552f340fc15
Content-Type: application/json

{
  "name": "Updated Building",
  "description": "Updated description",
  "numberFloor": 8,
  "imageCover": "updatedimage.jpg",
  "areaId": "2f81e4bb-6daf-4011-8974-ebb3fa59c117"

}
###
DELETE http://localhost:3000/building/1
