POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "john_doe",
    "password": "securePass123"
}

###
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNmM0NGI4Ni05NzYwLTRlNDUtYTVhOC01NWNlMDdjZDMzNWQiLCJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzM5NTE1MDMwLCJleHAiOjE3Mzk1MTg2MzB9.UXfzs8ZvFf5a87uQu-Ae256Xt4kpDoIuf7iZjMatxBM


###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john@example.com",
  "password": "securePass123",
  "phone": "123456789",
  "role": "Resident",
  "dateOfBirth": "1995-08-15T00:00:00.000Z",
  "gender": "Male"
}

### 
GET http://localhost:3000/auth/all-users


###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNmM0NGI4Ni05NzYwLTRlNDUtYTVhOC01NWNlMDdjZDMzNWQiLCJ1c2VybmFtZSI6ImpvaG5fZG9lIiwiaWF0IjoxNzM5NTEyODIxLCJleHAiOjE3Mzk1MTY0MjF9.0-YPrn99iB3gPwTVRyF6SVfidI-G3VxKgEt5GixwV_Q

###
GET http://localhost:3000/auth
Content-Type: application/json

{
    "username": "john_doe",
    "password": "securePass123"
}

#TODO: implement gRPC for this service. 
#TODO: Based on role of user created, create the related table (eg: user role Resident then create data Resident)
#TODO: CRUD for Resident, WorkingPositions, Departments, Employees
