POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "kha1",
    "password": "123"
}

###
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJqb2huIiwiaWF0IjoxNzM5MTE4ODkwLCJleHAiOjE3MzkyMDUyOTB9.D30dDdfdivzKDiYdexOzqU8E6WGEX3wm3kSWFH358bQ


###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john@example.com",
  "password": "securePass123",
  "phone": "123456789",
  "role": "Resident",
  "dateOfBirth": "1995-08-15T00:00:00.000Z",
  "gender": "Male"
}

### 
GET http://localhost:3000/auth/all-users


#TODO: Based on role of user created, create the related table (eg: user role Resident then create data Resident)
#FIXME: authorization, refresh token, logout, error message, user management, setup buildings microservice, docker, rabbitMQ, etc.