POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "john_doe",
    "password": "securePass123"
}

###
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjVjZTQ1OC02YzU0LTQ4NWItOTE2Yi1hOTRhZjVhOGY3MDUiLCJ1c2VybmFtZSI6Imh1eSIsInJvbGUiOiJSZXNpZGVudCIsImlhdCI6MTc0MDQ2NjQyOSwiZXhwIjoxNzQwNDcwMDI5fQ.F9W7Ov-d8wWwTEy7rTNVuN15hhMX8t97P7DGc8kC9Rc

###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "test",
  "email": "test@gmail.com",
  "password": "securePass123",
  "phone": "123456789",
  "role": "Resident",
  "dateOfBirth": "1995-08-15T00:00:00.000Z",
  "gender": "Male"
}

### 
GET http://localhost:3000/auth/all-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMyMTMxMiIsInVzZXJuYW1lIjoiam9obl9kb2UiLCJyb2xlIjoiUmVzaWRlbnQiLCJpYXQiOjE3Mzk4Nzg0MDYsImV4cCI6MTczOTg4MjAwNn0.Q69x0wm9LvrU7j0j2rbS7gOqfI_Y-66whk89dNnjQcw

###
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMyMTMxMiIsInVzZXJuYW1lIjoiam9obl9kb2UiLCJyb2xlIjoiUmVzaWRlbnQiLCJpYXQiOjE3Mzk4Nzg0MDYsImV4cCI6MTczOTg4MjAwNn0.Q69x0wm9LvrU7j0j2rbS7gOqfI_Y-66whk89dNnjQcw

###
GET http://localhost:3000/auth
Content-Type: application/json

{
    "username": "john_doe",
    "password": "securePass123"
}


###
GET http://localhost:3000/resident/all-residents
#TODO: Based on role of user created, create the related table (eg: user role Resident then create data Resident)
#TODO: CRUD for Resident, WorkingPositions, Departments, Employees
